name: Terraform

on: workflow_dispatch
 
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Extract Environment
        id: extract_env
        run: |
          # Remove the 'branch-' prefix to get the environment name
          export ENV_NAME="${GITHUB_REF#refs/heads/branch-}"
          echo "ENV_NAME=$ENV_NAME" >> $GITHUB_ENV
          
      - name: Terraform Init
        run: terraform init
      
      - name: Create or Select Terraform Workspace
        run: |
          terraform workspace list | grep -w "${{ env.ENV_NAME }}" || terraform workspace new "${{ env.ENV_NAME }}"
          terraform workspace select "${{ env.ENV_NAME }}"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var="environment=${{ env.ENV_NAME }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="environment=${{ env.ENV_NAME }}"
